"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-27 20:24:01.943333
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_rates",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate_to_base", sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint("day", "currency", name=op.f("pk_fx_rates")),
    )
    op.create_table(
        "securities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("exchange", sa.String(length=32), nullable=True),
        sa.Column("region", sa.String(length=2), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column("financial_currency", sa.String(length=3), nullable=True),
        sa.Column("sector", sa.String(length=128), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("sector_group", sa.String(length=16), nullable=True),
        sa.Column("universes", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_securities")),
        sa.UniqueConstraint("symbol", name=op.f("uq_securities_symbol")),
    )
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_securities_country"), ["country"], unique=False)
        batch_op.create_index(batch_op.f("ix_securities_isin"), ["isin"], unique=False)
        batch_op.create_index(batch_op.f("ix_securities_region"), ["region"], unique=False)
        batch_op.create_index(batch_op.f("ix_securities_sector"), ["sector"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "dividend_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("pay_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_dividend_events_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dividend_events")),
        sa.UniqueConstraint("security_id", "ex_date", name=op.f("uq_dividend_events_security_id")),
    )
    op.create_table(
        "financials_annual",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("revenue", sa.Double(), nullable=True),
        sa.Column("net_income", sa.Double(), nullable=True),
        sa.Column("eps", sa.Double(), nullable=True),
        sa.Column("operating_cashflow", sa.Double(), nullable=True),
        sa.Column("capex", sa.Double(), nullable=True),
        sa.Column("free_cashflow", sa.Double(), nullable=True),
        sa.Column("dividends_paid", sa.Double(), nullable=True),
        sa.Column("shares", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_financials_annual_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", "period_end", name=op.f("pk_financials_annual")),
    )
    op.create_table(
        "fundamentals",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("market_cap", sa.Double(), nullable=True),
        sa.Column("market_cap_eur", sa.Double(), nullable=True),
        sa.Column("eps_ttm", sa.Double(), nullable=True),
        sa.Column("eps_forward", sa.Double(), nullable=True),
        sa.Column("pe_ttm", sa.Double(), nullable=True),
        sa.Column("pe_forward", sa.Double(), nullable=True),
        sa.Column("price_to_book", sa.Double(), nullable=True),
        sa.Column("ev_to_ebitda", sa.Double(), nullable=True),
        sa.Column("dividend_yield", sa.Double(), nullable=True),
        sa.Column("dividend_rate", sa.Double(), nullable=True),
        sa.Column("payout_ratio", sa.Double(), nullable=True),
        sa.Column("five_year_avg_dividend_yield", sa.Double(), nullable=True),
        sa.Column("roe", sa.Double(), nullable=True),
        sa.Column("profit_margin", sa.Double(), nullable=True),
        sa.Column("revenue_growth", sa.Double(), nullable=True),
        sa.Column("earnings_growth", sa.Double(), nullable=True),
        sa.Column("debt_to_equity", sa.Double(), nullable=True),
        sa.Column("beta", sa.Double(), nullable=True),
        sa.Column("week52_high", sa.Double(), nullable=True),
        sa.Column("week52_low", sa.Double(), nullable=True),
        sa.Column("ma200", sa.Double(), nullable=True),
        sa.Column("target_mean_price", sa.Double(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_fundamentals_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_fundamentals")),
    )
    with op.batch_alter_table("fundamentals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fundamentals_market_cap_eur"), ["market_cap_eur"], unique=False
        )

    op.create_table(
        "price_history",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("close", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_price_history_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", "day", name=op.f("pk_price_history")),
    )
    op.create_table(
        "quotes",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Double(), nullable=True),
        sa.Column("previous_close", sa.Double(), nullable=True),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_quotes_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_quotes")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "fx_rate", sa.Numeric(precision=20, scale=10), server_default="1", nullable=False
        ),
        sa.Column("fees", sa.Numeric(precision=20, scale=6), server_default="0", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('buy', 'sell')", name=op.f("ck_transactions_kind")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_transactions_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_transactions_security_id_securities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transactions_security_id_trade_date"),
            ["security_id", "trade_date"],
            unique=False,
        )

    op.create_table(
        "valuations",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("dividend_ttm", sa.Double(), nullable=True),
        sa.Column("dividend_forward", sa.Double(), nullable=True),
        sa.Column("dividend_last_year", sa.Double(), nullable=True),
        sa.Column("dgr_5y", sa.Double(), nullable=True),
        sa.Column("dgr_10y", sa.Double(), nullable=True),
        sa.Column("growth_used", sa.Double(), nullable=True),
        sa.Column("years_no_cut", sa.Integer(), nullable=True),
        sa.Column("years_growth", sa.Integer(), nullable=True),
        sa.Column("yield_avg_5y", sa.Double(), nullable=True),
        sa.Column("yield_p80_5y", sa.Double(), nullable=True),
        sa.Column("yield_avg_10y", sa.Double(), nullable=True),
        sa.Column("yield_p80_10y", sa.Double(), nullable=True),
        sa.Column("pe_avg", sa.Double(), nullable=True),
        sa.Column("pe_years", sa.Integer(), nullable=True),
        sa.Column("payout_fcf", sa.Double(), nullable=True),
        sa.Column("payout_ocf", sa.Double(), nullable=True),
        sa.Column("fv_yield", sa.Double(), nullable=True),
        sa.Column("buy_yield", sa.Double(), nullable=True),
        sa.Column("fv_pe", sa.Double(), nullable=True),
        sa.Column("fv_chowder", sa.Double(), nullable=True),
        sa.Column("chowder_threshold", sa.Double(), nullable=True),
        sa.Column("fv_gordon", sa.Double(), nullable=True),
        sa.Column("max_price_target", sa.Double(), nullable=True),
        sa.Column("fair_value", sa.Double(), nullable=True),
        sa.Column("buy_price", sa.Double(), nullable=True),
        sa.Column("quality_ok", sa.Boolean(), nullable=True),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_valuations_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_valuations")),
    )
    op.create_table(
        "watchlist",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("margin_of_safety", sa.Double(), nullable=True),
        sa.Column("target_total_return", sa.Double(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_watchlist_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_watchlist")),
    )
    op.create_table(
        "dividend_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("dividend_event_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="expected", nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("pay_date", sa.Date(), nullable=False),
        sa.Column("shares", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("gross", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "withholding_origin",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "withholding_domestic",
            sa.Numeric(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "fx_rate", sa.Numeric(precision=20, scale=10), server_default="1", nullable=False
        ),
        sa.Column("net_base", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('expected', 'received')", name=op.f("ck_dividend_payments_status")
        ),
        sa.ForeignKeyConstraint(
            ["dividend_event_id"],
            ["dividend_events.id"],
            name=op.f("fk_dividend_payments_dividend_event_id_dividend_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_dividend_payments_security_id_securities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dividend_payments")),
        sa.UniqueConstraint(
            "dividend_event_id", name=op.f("uq_dividend_payments_dividend_event_id")
        ),
    )
    with op.batch_alter_table("dividend_payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dividend_payments_pay_date"), ["pay_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dividend_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dividend_payments_pay_date"))

    op.drop_table("dividend_payments")
    op.drop_table("watchlist")
    op.drop_table("valuations")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_security_id_trade_date"))

    op.drop_table("transactions")
    op.drop_table("quotes")
    op.drop_table("price_history")
    with op.batch_alter_table("fundamentals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fundamentals_market_cap_eur"))

    op.drop_table("fundamentals")
    op.drop_table("financials_annual")
    op.drop_table("dividend_events")
    op.drop_table("users")
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_securities_sector"))
        batch_op.drop_index(batch_op.f("ix_securities_region"))
        batch_op.drop_index(batch_op.f("ix_securities_isin"))
        batch_op.drop_index(batch_op.f("ix_securities_country"))

    op.drop_table("securities")
    op.drop_table("fx_rates")
    # ### end Alembic commands ###
